runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  login: admin
  script: app.app

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
  secure: always

builtins:
- deferred: on

env_variables:
  CONSUMER_KEY: ''
  CONSUMER_SECRET: ''
  ACCESS_TOKEN: ''
  ACCESS_TOKEN_SECRET: ''

skip_files:
- ^.git.*$
- ^.idea.*$
- ^.sass-cache.*$
- ^node_modules.*$
- ^neo4j.*$
- ^scripts.*$
- ^.*\.iml$
- ^.*\.pyc$
