runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: app.app

libraries:
- name: ssl
  version: latest

builtins:
- deferred: on

skip_files:
- ^.git.*$
- ^.idea.*$
- ^.sass-cache.*$
- ^node_modules.*$
- ^neo4j.*$
- ^scripts.*$
- ^.*\.iml$
- ^.*\.pyc$

env_variables:
  # ADD Consumer and Token Secrets
